language: ruby

services:
  - postgresql
rvm:
  - 2.4.0
before_install:
  - gem install bundler -v 1.15.1
notifications:
    - false
scripts:
  - bundle exec rspec spec
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:migrate
after_script:
  - bundle exec rake coveralls:push